--- 1.Which apps have the highest rating in the given available dataset?
select App, cast(Rating as float) as Rating from App where Rating = 5.0;

--- 2.What are the number of installs and reviews for the above apps? Return the apps with the highest reviews to the top.
select App, Rating, cast(Installs as float) as Installs, cast(Reviews as float) as Reviews from App order by Rating desc, Reviews desc;

--- 3. Which app has the highest number of reviews? Also, mention the number of reviews and category of the app.
select App, cast(Reviews as float) as Reviews, Category from App order by Reviews desc;

--- 4. What is the total amount of revenue generated by the google play store by hosting apps? (Whenever a user buys apps from the google play store, the amount is considered in the revenue).
select sum(cast(Installs as float)*cast(Price as float)) as Revenue from App where Type = 'Paid';

--- 5. Which Category of google play store apps has the highest number of installs? also, find out the total number of installs for that particular category.
select distinct(Category), cast(Installs as float) as Installs from App order by Installs desc;

select sum(cast(Installs as float)) as Total_Installs from App where Category = 'BOOKS_AND_REFERENCE';

--- 6. Which Genre has the most number of published apps?
select Genres, count(App) as Published_Apps from App group by Genres order by Published_Apps desc;

--- 7. Provide the list of all games ordered in such a way that the game that has the highest number of installs is displayed on the top (to avoid duplicate results use distinct)
select distinct(App), cast(Installs as float) as Installs from App where Category = 'Game' order by Installs desc;

--- 8. Provide the list of apps that can work on android version 4.0.3 and UP.
select App, "Android Ver" from App where "Android Ver" = '4.0.3 and UP';

--- 9. How many apps from the given data set are free? Also, provide the number of paid apps.
select App, Type from App where Type = 'Free';
select count(App) as Free_App from App where Type = 'Free' group by Type;

select App, Type from App where Type = 'Paid';
select count(App) as Paid_App from App where Type = 'Paid' group by Type;

--- 10. Which is the best dating app? (Best dating app is the one having the highest number of Reviews)
select App, Category, cast(Reviews as float) as Reviews from App where Category = 'Dating' order by Reviews desc;

--- 11.Get the number of reviews having positive sentiment and number of reviews having negative sentiment for the app 10 best foods for you and compare them.
select count(Translated_Review) as Negative_Count from Reviews where App = '10 Best Foods for You' and Sentiment = 'Negative';

select count(Translated_Review) as Postive_Count from Reviews where Sentiment = 'Positive' and App = '10 Best Foods for You';

--- 12. Which comments of ASUS SuperNote have sentiment polarity and sentiment subjectivity both as 1?
select Translated_Review, App, cast(Sentiment_Polarity as float) as Sentiment_Polarity, cast(Sentiment_Subjectivity as float) as Sentiment_Subjectivity from Reviews where App = 'ASUS SuperNote' and Sentiment_Polarity = 1.0 and Sentiment_Subjectivity = 1.0;

--- 13. Get all the neutral sentiment reviews for the app Abs Training-Burn belly fat
select Translated_Review, App,Sentiment from Reviews where App = 'Abs Training-Burn belly fat' and Sentiment = 'Neutral';

--- 14. Extract all negative sentiment reviews for Adobe Acrobat Reader with their sentiment polarity and sentiment subjectivity
select Translated_Review, App, Sentiment_Polarity, Sentiment_Subjectivity, Sentiment from Reviews where App = 'Adobe Acrobat Reader' and Sentiment = 'Negative';